### ISSUE TITLE
Check failed: st.ok() Non unique node name detected

### ISSUE THREAD

**Issue by prnysarker** [tensorflow/tfjs#2055]
For curiosity I wanted to convert COCO_SSD  saved_model to tensorflow js model, but I am getting the following error 
>  2019-09-17 22:19:09.670908: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-09-17 22:19:13.853712: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-09-17 22:19:13.857146: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-09-17 22:19:14.088168: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-09-17 22:19:14.090319: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
2019-09-17 22:19:14.092482: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
2019-09-17 22:19:24.094246: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-09-17 22:19:24.096482: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   debug_stripper: Graph size after: 8628 nodes (0), 13162 edges (0), time = 26.064ms.
2019-09-17 22:19:24.098886: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   model_pruner: Graph size after: 8219 nodes (-409), 12754 edges (-408), time = 124.274ms.
2019-09-17 22:19:24.101571: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 7005 nodes (-1214), 11333 edges (-1421), time = 994.332ms.
2019-09-17 22:19:24.104435: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   arithmetic_optimizer: Graph size after: 4839 nodes (-2166), 9181 edges (-2152), time = 306.565ms.
2019-09-17 22:19:24.106962: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   dependency_optimizer: Graph size after: 4817 nodes (-22), 9136 edges (-45), time = 95.869ms.
2019-09-17 22:19:24.109640: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   model_pruner: Graph size after: 4817 nodes (0), 9136 edges (0), time = 53.57ms.
2019-09-17 22:19:24.112096: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 4817 nodes (0), 9136 edges (0), time = 570.278ms.
2019-09-17 22:19:24.115057: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   arithmetic_optimizer: Graph size after: 4815 nodes (-2), 9132 edges (-4), time = 274.317ms.
2019-09-17 22:19:24.118129: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   dependency_optimizer: Graph size after: 4814 nodes (-1), 9130 edges (-2), time = 92.658ms.
2019-09-17 22:19:24.120591: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   debug_stripper: debug_stripper did nothing. time = 7.06ms.
2019-09-17 22:19:24.123030: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   model_pruner: Graph size after: 4814 nodes (0), 9130 edges (0), time = 44.256ms.
2019-09-17 22:19:24.125322: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 4814 nodes (0), 9130 edges (0), time = 314.737ms.
2019-09-17 22:19:24.127900: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   arithmetic_optimizer: Graph size after: 4814 nodes (0), 9130 edges (0), time = 290.724ms.
2019-09-17 22:19:24.130334: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   dependency_optimizer: Graph size after: 4814 nodes (0), 9130 edges (0), time = 98.029ms.
2019-09-17 22:19:24.133394: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   model_pruner: Graph size after: 4814 nodes (0), 9130 edges (0), time = 51.219ms.
2019-09-17 22:19:24.135981: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 4814 nodes (0), 9130 edges (0), time = 310.06ms.
2019-09-17 22:19:24.138364: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   arithmetic_optimizer: Graph size after: 4814 nodes (0), 9130 edges (0), time = 291.18ms.
2019-09-17 22:19:24.141163: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   dependency_optimizer: Graph size after: 4814 nodes (0), 9130 edges (0), time = 96.508ms.
2019-09-17 22:20:25.042127: F .\tensorflow/core/grappler/graph_view.h:332] Check failed: st.ok() Non unique node name detected: WeightSharedConvolutionalBoxPredictor/BoxPredictionTower/conv2d_3/weights

Command 
>>tensorflowjs_converter   --input_format=tf_saved_model --output_format=tfjs_graph_model --signature_name=serving_default --saved_model_tags=serve ./saved_model ./jsmodel

Hope I am not doing anything silly. very new to Tensorflow

**Comment by prnysarker** [comment]
I am using this model
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz

**Comment by prnysarker** [comment]
Hi , any update on this

**Comment by ezequielzacca** [comment]
Im having the same issue, did you find the solution?

**Comment by rthadur** [comment]
Hi @prnysarker did you follow this instructions [here](https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd#technical-details-for-advanced-users)  , if not please let us know your machine configuration, tfjs version , and the steps you were following , thank you

**Comment by prnysarker** [comment]
> I'm having the same issue, did you find the solution?

No still stuck only for this

**Comment by prnysarker** [comment]
> Hi @prnysarker did you follow this instructions [here](https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd#technical-details-for-advanced-users) , if not please let us know your machine configuration, tfjs version , and the steps you were following , thank you

Windows 10 64bit, 32gb Ram, Intel Core i7-8850H
versions : 
Python 3.6.8
tensorflowjs 1.2.9
Dependency versions:
  keras 2.2.4-tf
  tensorflow 1.14.0
  
By following your link 
TensorFlow.js model converters.: error: unrecognized arguments: --output_node_names='Postprocessor/ExpandDims_1,Postprocessor/Slice'

After removing --output_node_names flag 

Same error as above
 F .\tensorflow/core/grappler/graph_view.h:332] Check failed: st.ok() Non unique node name detected: WeightSharedConvolutionalBoxPredictor/BoxPredictionTower/conv2d_3/weights

**Comment by ezequielzacca** [comment]
I'm having exactly the same problem, the docs seem to be outdated since output_node_names it's unrecognized by the command

**Comment by rikenshah2002** [comment]
> For curiosity I wanted to convert COCO_SSD saved_model to tensorflow js model, but I am getting the following error
> 
> > 2019-09-17 22:19:09.670908: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> > 2019-09-17 22:19:13.853712: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
> > 2019-09-17 22:19:13.857146: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
> > 2019-09-17 22:19:14.088168: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
> > 2019-09-17 22:19:14.090319: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.002ms.
> > 2019-09-17 22:19:14.092482: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
> > 2019-09-17 22:19:24.094246: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
> > 2019-09-17 22:19:24.096482: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   debug_stripper: Graph size after: 8628 nodes (0), 13162 edges (0), time = 26.064ms.
> > 2019-09-17 22:19:24.098886: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   model_pruner: Graph size after: 8219 nodes (-409), 12754 edges (-408), time = 124.274ms.
> > 2019-09-17 22:19:24.101571: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 7005 nodes (-1214), 11333 edges (-1421), time = 994.332ms.
> > 2019-09-17 22:19:24.104435: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   arithmetic_optimizer: Graph size after: 4839 nodes (-2166), 9181 edges (-2152), time = 306.565ms.
> > 2019-09-17 22:19:24.106962: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   dependency_optimizer: Graph size after: 4817 nodes (-22), 9136 edges (-45), time = 95.869ms.
> > 2019-09-17 22:19:24.109640: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   model_pruner: Graph size after: 4817 nodes (0), 9136 edges (0), time = 53.57ms.
> > 2019-09-17 22:19:24.112096: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 4817 nodes (0), 9136 edges (0), time = 570.278ms.
> > 2019-09-17 22:19:24.115057: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   arithmetic_optimizer: Graph size after: 4815 nodes (-2), 9132 edges (-4), time = 274.317ms.
> > 2019-09-17 22:19:24.118129: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   dependency_optimizer: Graph size after: 4814 nodes (-1), 9130 edges (-2), time = 92.658ms.
> > 2019-09-17 22:19:24.120591: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   debug_stripper: debug_stripper did nothing. time = 7.06ms.
> > 2019-09-17 22:19:24.123030: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   model_pruner: Graph size after: 4814 nodes (0), 9130 edges (0), time = 44.256ms.
> > 2019-09-17 22:19:24.125322: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 4814 nodes (0), 9130 edges (0), time = 314.737ms.
> > 2019-09-17 22:19:24.127900: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   arithmetic_optimizer: Graph size after: 4814 nodes (0), 9130 edges (0), time = 290.724ms.
> > 2019-09-17 22:19:24.130334: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   dependency_optimizer: Graph size after: 4814 nodes (0), 9130 edges (0), time = 98.029ms.
> > 2019-09-17 22:19:24.133394: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   model_pruner: Graph size after: 4814 nodes (0), 9130 edges (0), time = 51.219ms.
> > 2019-09-17 22:19:24.135981: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 4814 nodes (0), 9130 edges (0), time = 310.06ms.
> > 2019-09-17 22:19:24.138364: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   arithmetic_optimizer: Graph size after: 4814 nodes (0), 9130 edges (0), time = 291.18ms.
> > 2019-09-17 22:19:24.141163: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   dependency_optimizer: Graph size after: 4814 nodes (0), 9130 edges (0), time = 96.508ms.
> > 2019-09-17 22:20:25.042127: F .\tensorflow/core/grappler/graph_view.h:332] Check failed: st.ok() Non unique node name detected: WeightSharedConvolutionalBoxPredictor/BoxPredictionTower/conv2d_3/weights
> 
> Command
> 
> > > tensorflowjs_converter   --input_format=tf_saved_model --output_format=tfjs_graph_model --signature_name=serving_default --saved_model_tags=serve ./saved_model ./jsmodel
> 
> Hope I am not doing anything silly. very new to Tensorflow

You can run tensorflowjs_conveter on Goggle Colab
And It worked for me!

**Comment by david201601** [comment]
I am facing the same issue :(
