### ISSUE TITLE
Mismatch in packed depthwise conv 2d results on Mali GPU

### ISSUE THREAD

**Issue by shanumantesc** [tensorflow/tfjs#6775]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes, test case shared below
- Mobile device : Pixel 6 Pro (Reproduces on any android device with Mali GPU that I tried)
- TensorFlow.js installed from (npm or script link): 3.19.0
- Browser version: Chrome 103.0.5060.53

**Describe the current behavior**
Packed depthwise conv2d produces incorrect result on Mali GPUs when `WEBGL_MAX_TEXTURE_SIZE` is left at the default value (which is 4096 on most modern android devices). In one of our networks, we end up creating a 3672x1 sized texture for weights, which produces incorrect outputs (presumably some error in sampling the texture, but that is just a guess). Setting max texture size lower than 3672 fixes the issue.

I have attached sample code below to produce the issue (uses the same filter dims as the layer which caused inaccuracy in our original network). The code does the following:
- We first run packed depthwise conv with 4096 as the texture size (the default value of max texture size on all browsers I tried, the value is hardcoded for consistent results)
- Next, we re-run the same node with a max size of 2048.
- Finally, we set backend to cpu to get the reference output.
- With size 2048, the outputs match the reference, but with the default size, the outputs do not match. 

Note: The mismatch occurs only on Mali GPUs with Android based on my tests. iOS, MacOS chrome, Androids with Adreno GPU all produce the correct result with default texture size (of 4096)

**Standalone code to reproduce the issue**
```
tf.ENV.set('WEBGL_PACK_DEPTHWISECONV', true)

let w = Array.from({length: 3 * 3 * 816}, () => Math.random())
let x = Array.from({length: 12 * 10 * 816}, () => Math.random())

let inputs = {
    filter: tf.tensor(w, [3, 3, 816, 1]),
    x: tf.tensor(x, [1, 12, 10, 816]),
    strides: 1,
    pad: [[0, 0], [1, 1], [1, 1], [0, 0]],
    dataFormat: "channelsLast",
    dilations: 1,
    activation: 'relu'
};

tf.setBackend('webgl')
tf.ENV.set('WEBGL_MAX_TEXTURE_SIZE', 4096)
let out_4096 = tf.fused.depthwiseConv2d(inputs);

tf.ENV.set('WEBGL_MAX_TEXTURE_SIZE', 2048)
inputs.x = tf.tensor(x, [1, 12, 10, 816])
inputs.filter = tf.tensor(w, [3, 3, 816, 1])
let out_2048 = tf.fused.depthwiseConv2d(inputs);

tf.setBackend('cpu')
inputs.x = tf.tensor(x, [1, 12, 10, 816])
inputs.filter = tf.tensor(w, [3, 3, 816, 1])
let out_reference = tf.fused.depthwiseConv2d(inputs);

const doTensorsDiffer = function(t0, t1) {
	return tf.any(tf.greater(tf.abs(tf.sub(t0, t1)), tf.scalar(1e-2))).dataSync()[0];
}

console.log("Default and 2048 differ? " + doTensorsDiffer(out_4096, out_2048));
console.log("Reference and 2048 differ? " + doTensorsDiffer(out_reference, out_2048));
console.log("Reference and 4096 differ? " + doTensorsDiffer(out_reference, out_4096));
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by RamiSJ12** [comment]
tf.ENV.set('WEBGL_PACK_DEPTHWISECONV', true)

let w = Array.from({length: 3 * 3 * 816}, () => Math.random())
let x = Array.from({length: 12 * 10 * 816}, () => Math.random())

let inputs = {
    filter: tf.tensor(w, [3, 3, 816, 1]),
    x: tf.tensor(x, [1, 12, 10, 816]),
    strides: 1,
    pad: [[0, 0], [1, 1], [1, 1], [0, 0]],
    dataFormat: "channelsLast",
    dilations: 1,
    activation: 'relu'
};

tf.setBackend('webgl')
tf.ENV.set('WEBGL_MAX_TEXTURE_SIZE', 4096)
let out_4096 = tf.fused.depthwiseConv2d(inputs);

tf.ENV.set('WEBGL_MAX_TEXTURE_SIZE', 2048)
inputs.x = tf.tensor(x, [1, 12, 10, 816])
inputs.filter = tf.tensor(w, [3, 3, 816, 1])
let out_2048 = tf.fused.depthwiseConv2d(inputs);

tf.setBackend('cpu')
inputs.x = tf.tensor(x, [1, 12, 10, 816])
inputs.filter = tf.tensor(w, [3, 3, 816, 1])
let out_reference = tf.fused.depthwiseConv2d(inputs);

const doTensorsDiffer = function(t0, t1) {
	return tf.any(tf.greater(tf.abs(t0.sub(t1)), tf.scalar(1e-2))).dataSync()[0];
}

console.log("Default and 2048 differ? " + doTensorsDiffer(out_4096, out_2048));
console.log("Reference and 2048 differ? " + doTensorsDiffer(out_reference, out_2048));
console.log("Reference and 4096 differ? " + doTensorsDiffer(out_reference, out_4096));

**Comment by Linchenn** [comment]
@shanumantesc I just have a quick update for this issue, even though I am still working on this issue. The happens most likely because of Mali GPU's precision. Specifically, the interpolated values for WebGL varyings by Mali GPU are not accurate enough. 

Let me figure out if I could find out any solutions to help you and will reach out to you soon.

(You could stop reading at here, except you are interested in the details.)
## Experiments
I am using the following scripts on browsers to check varying values for 3672 points in range [0, 1].
```js
"use strict";

var vs = `#version 300 es
in vec4 position;
in vec2 uv;
out vec2 v_texcoord;

void main() {
  gl_Position = position;
  v_texcoord = uv;
}
`;

var colorFS = `#version 300 es

precision highp float;

in vec2 v_texcoord;
out vec4 fragColor;

void main() {
    fragColor = vec4(v_texcoord, 0, 0);
}
`;

function createShader(gl, source, type) {
  var shader = gl.createShader(type);
  gl.shaderSource(shader, source);
  gl.compileShader(shader);
  return shader;
}

function createProgram(gl, vertexShaderSource, fragmentShaderSource) {
  var program = gl.createProgram();
  var vshader = createShader(gl, vertexShaderSource, gl.VERTEX_SHADER);
  var fshader = createShader(gl, fragmentShaderSource, gl.FRAGMENT_SHADER);
  gl.attachShader(program, vshader);
  gl.deleteShader(vshader);
  gl.attachShader(program, fshader);
  gl.deleteShader(fshader);
  gl.linkProgram(program);

  var log = gl.getProgramInfoLog(program);
  if (log) {
    console.log(log);
  }

  log = gl.getShaderInfoLog(vshader);
  if (log) {
    console.log(log);
  }

  log = gl.getShaderInfoLog(fshader);
  if (log) {
    console.log(log);
  }

  return program;
};


function createTextureAndFramebuffer(gl, width, height) {
  const tex = gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D, tex);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
  gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, width, height, 0, gl.RGBA, gl.FLOAT, null);
  const fb = gl.createFramebuffer();
  gl.bindFramebuffer(gl.FRAMEBUFFER, fb);
  gl.framebufferTexture2D(
     gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, tex, 0);
  return {tex: tex, fb: fb};
}

// Run the shader program.
const gl = document.createElement("canvas").getContext("webgl2");
gl.getExtension('EXT_color_buffer_float');
const colorProgram = createProgram(gl, vs, colorFS);
const width = 1;
const height = 3672;
// make 2 textures by attaching them to framebuffers and rendering to them
const texFbPair1 = createTextureAndFramebuffer(gl, width, height);

const buf = gl.createBuffer();
gl.bindBuffer(gl.ARRAY_BUFFER, buf);
gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([
  -1, -1, 0, 0,
   1, -1, 1, 0,
  -1,  1, 0, 1,
  -1,  1, 0, 1,
   1, -1, 1, 0,
   1,  1, 1, 1
]), gl.STATIC_DRAW);
  
gl.bindBuffer(gl.ARRAY_BUFFER, buf);
const colorPrgPositionLoc = gl.getAttribLocation(colorProgram, "position");
gl.enableVertexAttribArray(colorPrgPositionLoc);
gl.vertexAttribPointer(colorPrgPositionLoc, 2, gl.FLOAT, false, 16, 0);
gl.bindBuffer(gl.ARRAY_BUFFER, buf);
const colorPrgUvLoc = gl.getAttribLocation(colorProgram, "uv");
gl.enableVertexAttribArray(colorPrgUvLoc);
gl.vertexAttribPointer(colorPrgUvLoc, 2, gl.FLOAT, false, 16, 8);
gl.useProgram(colorProgram);
gl.bindFramebuffer(gl.FRAMEBUFFER, texFbPair1.fb);
gl.viewport(0, 0, width, height);
gl.drawArrays(gl.TRIANGLES, 0, 6);


// Prepare to logout the shader program's outputs.
const fb = texFbPair1.fb
gl.bindFramebuffer(gl.FRAMEBUFFER, fb)
const packedRGBA = new Float32Array(width * height * 4);
gl.readPixels(
          0, 0, width, height, gl.RGBA, gl.FLOAT, packedRGBA);


// Log out first 10 values for varyings.
const ys = packedRGBA.filter((e, i) => i%4===1);
console.log(ys.slice(0, 10).join('\n'));
```

## Result analysis
On Pixel 6 Pro (Mali-G78 MP20), the browser would log out:
```
0.00034618377685546875
0.0006189346313476562
0.0008907318115234375
0.001163482666015625
0.0014352798461914062
0.0017080307006835938
0.001979827880859375
0.0022525787353515625
0.0025243759155273438
0.0027971267700195312
```
The difference between any two continuous values are 0.0002727508545 or 0.0002717971802. Then `1 / 0.0002717971802 = 3666` or `1 / 0.0002717971802 = 3679`, but `3666` or `3679` is supposed to be 3672.

On Xiaomi Redmi Note 11 (Adreno 610), the browser would log out:
```
0.0001361655741
0.0004084967077
0.0006808278849
0.000953159004
0.001225490123
0.0014978213
0.001770152478
0.002042483538
0.002314814832
0.002587145893
```

The difference between any two continuous values are around 0.00027233 and `1 / 0.00027233 = 3672`, which is **correct**.


On Macbook pro, the browser would log out:
```
0.0001361655741
0.0004084967077
0.0006808278267
0.0009531589458
0.001225490123
0.001497821184
0.001770152361
0.002042483306
0.002314814599
0.00258714566
```

The difference between any two continuous values are also around 0.00027233 and `1 / 0.00027233 = 3672`, which is **correct**.

**Comment by shanumantesc** [comment]
@Linchenn really interesting analysis, thanks for digging into this! An interesting followup where I set width to 2 and height as 3672

```
let width = 2;
let height = 3672;
let texFbPair1 = createTextureAndFramebuffer(gl, width, height);

let buf = gl.createBuffer();
gl.bindBuffer(gl.ARRAY_BUFFER, buf);
gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([
  -1, -1, 0, 0,
   1, -1, 1, 0,
  -1,  1, 0, 1,
  -1,  1, 0, 1,
   1, -1, 1, 0,
   1,  1, 1, 1
]), gl.STATIC_DRAW);
  
gl.bindBuffer(gl.ARRAY_BUFFER, buf);
let colorPrgPositionLoc = gl.getAttribLocation(colorProgram, "position");
gl.enableVertexAttribArray(colorPrgPositionLoc);
gl.vertexAttribPointer(colorPrgPositionLoc, 2, gl.FLOAT, false, 16, 0);
gl.bindBuffer(gl.ARRAY_BUFFER, buf);
let colorPrgUvLoc = gl.getAttribLocation(colorProgram, "uv");
gl.enableVertexAttribArray(colorPrgUvLoc);
gl.vertexAttribPointer(colorPrgUvLoc, 2, gl.FLOAT, false, 16, 8);
gl.useProgram(colorProgram);
gl.bindFramebuffer(gl.FRAMEBUFFER, texFbPair1.fb);
gl.viewport(0, 0, width, height);
gl.drawArrays(gl.TRIANGLES, 0, 6);


// Prepare to logout the shader program's outputs.
let fb = texFbPair1.fb
gl.bindFramebuffer(gl.FRAMEBUFFER, fb)
let packedRGBA = new Float32Array(width * height * 4);
gl.readPixels(
          0, 0, width, height, gl.RGBA, gl.FLOAT, packedRGBA);


let ys = packedRGBA.filter((e, i) => i%(4*width)===1);
for (var i = 0; i < 10; i += 1) {
  console.log(ys[i+1] + ":" + ys[i] + " Diff: " + 1/(ys[i+1] - ys[i]))
}
```

In this case I get
```
0.0005092620849609375:0.00023698806762695312 Diff: 3672.77057793345
0.0007815361022949219:0.0005092620849609375 Diff: 3672.77057793345
0.0010538101196289062:0.0007815361022949219 Diff: 3672.77057793345
0.0013260841369628906:0.0010538101196289062 Diff: 3672.77057793345
0.001598358154296875:0.0013260841369628906 Diff: 3672.77057793345
0.0018706321716308594:0.001598358154296875 Diff: 3672.77057793345
0.0021429061889648438:0.0018706321716308594 Diff: 3672.77057793345
0.0024156570434570312:0.0021429061889648438 Diff: 3666.3496503496503
0.0026879310607910156:0.0024156570434570312 Diff: 3672.77057793345
0.002960205078125:0.0026879310607910156 Diff: 3672.77057793345
```
So this is closer to what we would want. Although we are always off by 1 with NN sampling per my understanding and there is also one case where diff is still wrong `3666.3496503496503` . As I increase the width beyond to, I still see this pattern of `3672.77057793345` and `3669.557305336833` popping up, but it is better than width 1 🤔

**Comment by shanumantesc** [comment]
The issue is not even with large texture size, even with `width = 1; height = 2000` , I get
```
0.0008230209350585938:0.00032329559326171875 Diff: 2001.0992366412213
0.0013227462768554688:0.0008230209350585938 Diff: 2001.0992366412213
0.0018224716186523438:0.0013227462768554688 Diff: 2001.0992366412213
0.002323150634765625:0.0018224716186523438 Diff: 1997.287619047619
0.0028228759765625:0.002323150634765625 Diff: 2001.0992366412213
0.003322601318359375:0.0028228759765625 Diff: 2001.0992366412213
0.00382232666015625:0.003322601318359375 Diff: 2001.0992366412213
0.004323005676269531:0.00382232666015625 Diff: 1997.287619047619
0.004822731018066406:0.004323005676269531 Diff: 2001.0992366412213
0.005322456359863281:0.004822731018066406 Diff: 2001.0992366412213
```

this is sampling the wrong UV. But this issue goes away if the width is >= 8 🤷‍♂️  I have no explanation for why the UV values would be linked to what I set as the width. Powers of 2 work correctly irrespective of size, ie a height of 4096 has no floating point issues (as expected given that mantissa will be 0)

And that leaves the question of how do we know at runtime whether we are guaranteed to sample the correct pixel on Mali GPUs.

**Comment by Linchenn** [comment]
I just found Mali GPU could correctly compute `1/3672 = 0.00027233114815317094` with the following fs shader:
```js
var colorFS = `#version 300 es
precision highp float;

in mediump vec2 v_texcoord;
out vec4 fragColor;

void main() {
    fragColor = vec4(0, 1.0/3672.0, 0, 0);
}
`;
```

I am currently finding a way to increase the precision of varying's interpolation.

Of course, we could also consider the ways to fix it in runtime.

**Comment by shanumantesc** [comment]
The driver could have calculated the float value during compilation given that it is constant. I guess we'd have to pass in 3672 in a uniform and then force the division at runtime to be extra sure.

**Comment by Linchenn** [comment]
Good catch, but I got the same correct results when I using the following fragment shader:
```
var colorFS = `#version 300 es
precision highp float;

in vec2 v_texcoord;
out vec4 fragColor;
uniform float color;

void main() {
    fragColor = vec4(color, 1.0/color, 0, 0);
}
`;
```

I set color as 3672, and the output is still `3672, 0.00027233114815317094, 0, 0`

**Comment by Linchenn** [comment]
@shanumantesc We found out a potential solution to solve this ISSUE, and we want to see if you have any suggestions over it.

## Reasons for the mismatch
According to the results from the above experiments, we know that the more squarish the texture is, the better the of the varying's precision is and the less we rely on the varying's precision. ('squarish' means the ratio of height/width is close to 1)

The mismatch you described above happens because of the filter `[3, 3, 816, 1]` is not uploaded to Mali GPU correctly. Specifically, all tensors will be uploaded to a 2D WebGL texture and the shape of the texture is computed through [getTextureShapeFromLogicalShape](https://github.com/tensorflow/tfjs/blob/d931cc7f3fb3738f4397b920991ac656f6bd516b/tfjs-backend-webgl/src/webgl_util.ts#L368).

Then, by default (`WEBGL_MAX_TEXTURE_SIZE ` is 4096), the texture shape of the filter would become [3672, 1], and the ratio of texture's `height/width=3672` is too large. However, if you set `WEBGL_MAX_TEXTURE_SIZE ` as 2048, the texture shape is squarish-ed, lowering the ratio of height/width, so the problem of Mali's varying precision did not appear.

## Potential solution
Currently, [getTextureShapeFromLogicalShape](https://github.com/tensorflow/tfjs/blob/d931cc7f3fb3738f4397b920991ac656f6bd516b/tfjs-backend-webgl/src/webgl_util.ts#L368) squarish texture shape only if the width or the height exceed `WEBGL_MAX_TEXTURE_SIZE`. 

### We could offer
Now, we know the texture shape is also supposed to be squarish-ed if the ratio of height/width (aspect ratio) is too large. So, we plan to expose a flag `TEXTURE_ASPECT_RATIO_THRESHOL` and let users to set it. Then, if the texture shape's aspect ratio exceeds `TEXTURE_ASPECT_RATIO_THRESHOL`, the texture will be squarish-ed.

### You could do
With this flag exposed, you could set `TEXTURE_ASPECT_RATIO_THRESHOL` to a certain value for the devices with Mali GPU in your application. For example:
```js
const gl = tf.backend().gpgpu.gl;
const dbgRenderInfo = gl.getExtension('WEBGL_debug_renderer_info');
const webglRenderer = gl.getParameter(dbgRenderInfo.UNMASKED_RENDERER_WEBGL);
if (webglRenderer.includes('Mali')) {
    tf.env().set('TEXTURE_ASPECT_RATIO_THRESHOL', 2048);
}
```

## Others
I did not find out a way to correct Mali GPU's interpolation for varying. From the reply of https://community.arm.com/support-forums/f/graphics-gaming-and-vr-forum/48206/issue-about-the-inaccurate-varying-value-through-interpolation, it looks like interpolation precision differences are to be expected across devices. If you have ideas about, I am happy to consider them.

**Comment by shanumantesc** [comment]
Thanks for the investigation @Linchenn !

> The mismatch you described above happens because of the filter [3, 3, 816, 1] is not uploaded to Mali GPU correctly.

Per my understanding, the issue is not with upload, but rather with sampling, is that correct?

> Then, if the texture shape's aspect ratio exceeds TEXTURE_ASPECT_RATIO_THRESHOL, the texture will be squarish-ed.

I tested the case of 3672x3672 texture, and can still see off-by-1 errors in the resulting difference between consecutive pixels in height or width dimension. In this case, it looks like we need to also cap the maximum texture dimension. Based on some experiments on Pixel 6, this max dimension seems to be ~2650 after which we start getting off-by-1 errors with NN sampling for square textures.

 But I suppose there is no way to avoid this case? If there is a layer that needs a square-ish texture larger than 2650 in one dimension, then it is likely going to have some inaccuracy and we can't do anything about it for Mali devices.

Using `TEXTURE_ASPECT_RATIO_THRESHOLD` will solve the issue for atleast some of the cases, so I don't mind going ahead with this workaround for now.

>  it looks like interpolation precision differences are to be expected across devices. If you have ideas about, I am happy to consider them.

That article seems to mention to use `precision highp` to fix the issue, but it didn't help when I tried locally. I'll try to file a bug with ARM and see if they have any pointers. I used https://webgl2fundamentals.org/webgl/webgl-precision-lowp-mediump-highp.html as a way to know the device precision and got the following result

Mali (Pixel6 Pro)
<img width="271" alt="Screen Shot 2022-08-26 at 6 28 12 PM" src="https://user-images.githubusercontent.com/71482681/187008977-354ab01c-0386-47f9-942c-c42913213c77.png">

Adreno (Galaxy s22)
<img width="304" alt="Screen Shot 2022-08-26 at 6 28 46 PM" src="https://user-images.githubusercontent.com/71482681/187008981-73d22727-ad7c-4d24-ab09-a7ba6802bcbd.png">

so highp seems to have the same number of precision bits on both platforms, but maybe it is getting ignored?

**Comment by Linchenn** [comment]
@shanumantesc 
> Per my understanding, the issue is not with upload, but rather with sampling, is that correct? 

Correct, I mean the issue comes from `uploadToGpu` function and smapling is involved in it.

> I tested the case of 3672x3672 texture, and can still see off-by-1 errors in the resulting difference between consecutive pixels in height or width dimension. In this case, it looks like we need to also cap the maximum texture dimension. Based on some experiments on Pixel 6, this max dimension seems to be ~2650 after which we start getting off-by-1 errors with NN sampling for square textures.
> 
> But I suppose there is no way to avoid this case? If there is a layer that needs a square-ish texture larger than 2650 in one dimension, then it is likely going to have some inaccuracy and we can't do anything about it for Mali devices?

Yeah, using `WEBGL_MAX_TEXTURE_SIZE` in your application to cap the maximum texture dimension helps.

Also, as I remember, you mentioned 'Powers of 2 work correctly irrespective of size', so I am considerring if enforce the length of height to be a 'power of 2' works here. Specifically, we may expose a flag `TEXTURE_EDGE_LENGTH_THRESHOLD_TO_SQUARISH`, instead of `TEXTURE_ASPECT_RATIO_THRESHOLD ` and, if any edge length is larger than the flag value, the texture shape will become `[power2, size/power2]` (`power2` is some power of 2 value)?

> That article seems to mention to use `precision highp` to fix the issue, but it didn't help when I tried locally. I'll try to file a bug with ARM and see if they have any pointers. I used https://webgl2fundamentals.org/webgl/webgl-precision-lowp-mediump-highp.html as a way to know the device precision and got the following result

Thank you for helping on this! If you have it, could you cc me?

**Comment by kenrussell** [comment]
From the investigation done here already it sounds like it would be difficult to try to work around this varying interpolation precision issue in the WebGL implementation. If TF.js isn't already using GLSL's `texelFetch` primitive when running on top of WebGL 2.0, combined with manual calculation of the texel indices into these textures - has that been tried?

**Comment by shanumantesc** [comment]
> Also, as I remember, you mentioned 'Powers of 2 work correctly irrespective of size', so I am considerring if enforce the length of height to be a 'power of 2' works here. Specifically, we may expose a flag TEXTURE_EDGE_LENGTH_THRESHOLD_TO_SQUARISH, instead of TEXTURE_ASPECT_RATIO_THRESHOLD and, if any edge length is larger than the flag value, the texture shape will become [power2, size/power2] (power2 is some power of 2 value)?

Yes, forcing the larger texture dimension to be power of 2 would also work for us. I did a quick test on our model, and it fixes the accuracy issue as expected. However, we might still run into issues with sampling the non-pot (power of 2) dimension like you said, and it is hard to predict when exactly this will fail. Overall, either aspect ratio threshold or force to POT flag works for us. I'd prefer POT flag since atleast one of the dimensions is guaranteed to be sampled correctly.

> Thank you for helping on this! If you have it, could you cc me?

Will let you know once I have the issue.

Also, trying `texelFetch` as suggested above seems like a promising alternative.

**Comment by shanumantesc** [comment]
> Also, trying texelFetch as suggested above seems like a promising alternative.

Thinking about this a bit more, if the issue is with varying precision, then even if we calculate something like
```
in ivec2 texSize;
in vec2 uv;
uniform sampler2D in_texture;

ivec2 pixelCoord = uv * texSize;
vec4 color = texelFetch(in_texture, pixelCoord, 0);
...
```
that would still not help, right @kenrussell ? Or are you suggesting some other way to figure out the pixel coordinate without using varyings like `gl_FragCoord`?

**Comment by kenrussell** [comment]
It's not completely clear to me. In the test case above, for example, some of the vertices have homogeneous coordinate `w=0`, which I don't understand - it seems to me those will go to infinity, so I'm still unclear on whether there is really a bug in the interpolation of varyings.

Since the results become more and more correct the wider the texture becomes, there might still just be a bug in texture sampling. The number of bits of precision in the tables above should be sufficient to exactly represent all of the values between 0 and 4096. Maybe the bug is actually related to interpolation of varyings for degenerate triangles, if a long skinny triangle is being used to sample the long skinny texture. I'd still suggest trying `texelFetch` and seeing if feeding in appropriate geometry and UVs can reach every texel.

**Comment by shanumantesc** [comment]
I tried changing the vertex shader posted by @Linchenn to 
```
var vs = `#version 300 es
precision highp float;
in vec4 position;
in vec2 uv;
out vec2 v_texcoord;

void main() {
  gl_Position = vec4(position.xy, 0.0, 1.0);
  v_texcoord = uv;
}
`;
```
but still get the same (incorrect) result on a Mali device when writing out the uvs to output color.

> Maybe the bug is actually related to interpolation of varyings for degenerate triangles, if a long skinny triangle is being used to sample the long skinny texture.

Yeah, that was my thinking as well.

> I'd still suggest trying texelFetch and seeing if feeding in appropriate geometry and UVs can reach every texel.

I tried the following which uses both texelFetch and UV sampling, and both of these methods produce incorrect output (output doesn't match expected) only on Mali GPU.
 
```
let drawTextureAndGetOutput = function(width, height, pixelData, useTexelFetch) {

  var vs = `#version 300 es
  precision highp float;
  in vec4 position;
  in vec2 uv;
  out vec2 v_texcoord;

  void main() {
    gl_Position = vec4(position.xy, 0.0, 1.0);
    v_texcoord = vec2(0.0, 0.0);
    v_texcoord = uv;
  }
  `;

  var colorFS = `#version 300 es

  precision highp float;
  precision highp int;
  precision highp sampler2D;

  in vec2 v_texcoord;
  uniform sampler2D in_texture;

  out vec4 fragColor;

  void main() {
    vec2 centerCoord =  v_texcoord * vec2(textureSize(in_texture, 0));
    ivec2 pixelCoord = ivec2(floor(centerCoord));
    fragColor = ${useTexelFetch} ? texelFetch(in_texture, pixelCoord, 0) : texture(in_texture, v_texcoord);
  }
  `;

  function createShader(gl, source, type) {
    var shader = gl.createShader(type);
    gl.shaderSource(shader, source);
    gl.compileShader(shader);
    return shader;
  }

  function createProgram(gl, vertexShaderSource, fragmentShaderSource) {
    var program = gl.createProgram();
    var vshader = createShader(gl, vertexShaderSource, gl.VERTEX_SHADER);
    var fshader = createShader(gl, fragmentShaderSource, gl.FRAGMENT_SHADER);
    gl.attachShader(program, vshader);
    gl.deleteShader(vshader);
    gl.attachShader(program, fshader);
    gl.deleteShader(fshader);
    gl.linkProgram(program);

    var log = gl.getProgramInfoLog(program);
    if (log) {
      console.log(log);
    }

    log = gl.getShaderInfoLog(vshader);
    if (log) {
      console.log(log);
    }

    log = gl.getShaderInfoLog(fshader);
    if (log) {
      console.log(log);
    }

    return program;
  };

  const gl = document.createElement("canvas").getContext("webgl2");
  gl.getExtension('EXT_color_buffer_float');
  const colorProgram = createProgram(gl, vs, colorFS);
  gl.useProgram(colorProgram);


  function createTextureAndFramebuffer(gl, width, height) {
    const tex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, width, height, 0, gl.RGBA, gl.FLOAT, null);
    const fb = gl.createFramebuffer();
    gl.bindFramebuffer(gl.FRAMEBUFFER, fb);
    gl.framebufferTexture2D(
       gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, tex, 0);
    return {tex: tex, fb: fb};
  }


  function createTextureForRead(gl, width, height) {
    const tex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, width, height, 0, gl.RGBA, gl.FLOAT, pixelData);
    return tex;
  }
  let texFbPair1 = createTextureAndFramebuffer(gl, width, height);

  let texForRead = createTextureForRead(gl, width, height, data);

  let buf = gl.createBuffer();
  gl.bindBuffer(gl.ARRAY_BUFFER, buf);
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([
    -1,  1, 0.0, 1.0,
     1, -1, 1.0, 0.0,
     1,  1, 1.0, 1.0,
    -1, -1, 0.0, 0.0,
     1, -1, 1.0, 0.0,
    -1,  1, 0.0, 1.0,
  ]), gl.STATIC_DRAW);
    
  gl.bindBuffer(gl.ARRAY_BUFFER, buf);
  let colorPrgPositionLoc = gl.getAttribLocation(colorProgram, "position");
  gl.enableVertexAttribArray(colorPrgPositionLoc);
  gl.vertexAttribPointer(colorPrgPositionLoc, 2, gl.FLOAT, false, 16, 0);
  gl.bindBuffer(gl.ARRAY_BUFFER, buf);
  let colorPrgUvLoc = gl.getAttribLocation(colorProgram, "uv");
  gl.enableVertexAttribArray(colorPrgUvLoc);
  gl.vertexAttribPointer(colorPrgUvLoc, 2, gl.FLOAT, false, 16, 8);

  var textureLoc = gl.getUniformLocation(colorProgram, "in_texture");
  var unit = 2;
  gl.activeTexture(gl.TEXTURE0 + unit);
  gl.bindTexture(gl.TEXTURE_2D, texForRead);
  gl.uniform1i(textureLoc, unit);

  gl.bindFramebuffer(gl.FRAMEBUFFER, texFbPair1.fb);
  gl.viewport(0, 0, width, height);
  gl.drawArrays(gl.TRIANGLES, 0, 6);


  // Prepare to log out the shader program's outputs.
  let fb = texFbPair1.fb
  gl.bindFramebuffer(gl.FRAMEBUFFER, fb)
  let packedRGBA = new Float32Array(width * height * 4);
  gl.readPixels(0, 0, width, height, gl.RGBA, gl.FLOAT, packedRGBA);
  return packedRGBA;
}

let width = 1;
let height = 3672;
let data = new Float32Array(Array.from({length: width * height * 4}, () => Math.random()));
let outputWithTexelFetch = drawTextureAndGetOutput(width, height, data, true);
let outputWithTextureSample = drawTextureAndGetOutput(width, height, data, false);

var compareArrays = function(array0, array1) {
  var mismatchCount = 0;
  for (var i = 0; i < array0.length; ++i) {
    if (array0[i] != array1[i]) {
      console.log("TexelFetch data differs at index " + Math.floor(i/4) + "," + (i%4) + ". Expected:" + array0[i] + " Actual:" + array1[i])
      mismatchCount++;
      if (mismatchCount > 10) {
        break;
      }
    }
  }
}

console.log(">>>>> Comparing outputWithTexelFetch");
compareArrays(data, outputWithTexelFetch);
console.log(">>>>> Comparing outputWithTextureSample");
compareArrays(data, outputWithTextureSample);
console.log(">>>>> Comparing outputWithTexelFetch vs outputWithTextureSample");
compareArrays(outputWithTexelFetch, outputWithTextureSample);
```

**Comment by kenrussell** [comment]
```
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([
    -1,  1, 0.0, 1.0,
     1, -1, 1.0, 0.0,
     1,  1, 1.0, 1.0,
    -1, -1, 0.0, 0.0,
     1, -1, 1.0, 0.0,
    -1,  1, 0.0, 1.0,
  ]), gl.STATIC_DRAW);
```

Could you please try changing this to the following?

```
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([
    -1,  1, 0.0, 1.0,
     1, -1, 0.0, 1.0,
     1,  1, 0.0, 1.0,
    -1, -1, 0.0, 1.0,
     1, -1, 0.0, 1.0,
    -1,  1, 0.0, 1.0,
  ]), gl.STATIC_DRAW);
```

I don't understand why some of the vertices are using `z=0` and some `z=1`, and especially why some are using `w=0` (which will cause a division by zero to the best of my understanding) and some `w=1`. Please try using these vertices which are firmly in the `z=0` plane.

**Comment by shanumantesc** [comment]
I was using `gl_Position = vec4(position.xy, 0.0, 1.0);` in the vertex shader in the previous example, so the zw components for the vertices shouldn't matter per my understanding.

I also tried changing to the following as suggested (note: the uvs and vertices are provided in the same buffer, but now we add 2 more entries for the uvs instead of using the last 2 vertex positions), but get the same (incorrect) results on Mali
```
let drawTextureAndGetOutput = function(width, height, pixelData, useTexelFetch) {

  var vs = `#version 300 es
  precision highp float;
  in vec4 position;
  in vec2 uv;
  out vec2 v_texcoord;

  void main() {
    gl_Position = position;
    v_texcoord = vec2(0.0, 0.0);
    v_texcoord = uv;
  }
  `;

  var colorFS = `#version 300 es

  precision highp float;
  precision highp int;
  precision highp sampler2D;

  in vec2 v_texcoord;
  uniform sampler2D in_texture;

  out vec4 fragColor;

  void main() {
    vec2 centerCoord =  v_texcoord * vec2(textureSize(in_texture, 0));
    ivec2 pixelCoord = ivec2(floor(centerCoord));
    fragColor = ${useTexelFetch} ? texelFetch(in_texture, pixelCoord, 0) : texture(in_texture, v_texcoord);
  }
  `;

  function createShader(gl, source, type) {
    var shader = gl.createShader(type);
    gl.shaderSource(shader, source);
    gl.compileShader(shader);
    return shader;
  }

  function createProgram(gl, vertexShaderSource, fragmentShaderSource) {
    var program = gl.createProgram();
    var vshader = createShader(gl, vertexShaderSource, gl.VERTEX_SHADER);
    var fshader = createShader(gl, fragmentShaderSource, gl.FRAGMENT_SHADER);
    gl.attachShader(program, vshader);
    gl.deleteShader(vshader);
    gl.attachShader(program, fshader);
    gl.deleteShader(fshader);
    gl.linkProgram(program);

    var log = gl.getProgramInfoLog(program);
    if (log) {
      console.log(log);
    }

    log = gl.getShaderInfoLog(vshader);
    if (log) {
      console.log(log);
    }

    log = gl.getShaderInfoLog(fshader);
    if (log) {
      console.log(log);
    }

    return program;
  };

  const gl = document.createElement("canvas").getContext("webgl2");
  gl.getExtension('EXT_color_buffer_float');
  const colorProgram = createProgram(gl, vs, colorFS);
  gl.useProgram(colorProgram);


  function createTextureAndFramebuffer(gl, width, height) {
    const tex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, width, height, 0, gl.RGBA, gl.FLOAT, null);
    const fb = gl.createFramebuffer();
    gl.bindFramebuffer(gl.FRAMEBUFFER, fb);
    gl.framebufferTexture2D(
       gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, tex, 0);
    return {tex: tex, fb: fb};
  }


  function createTextureForRead(gl, width, height) {
    const tex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, width, height, 0, gl.RGBA, gl.FLOAT, pixelData);
    return tex;
  }
  let texFbPair1 = createTextureAndFramebuffer(gl, width, height);

  let texForRead = createTextureForRead(gl, width, height, data);

  let buf = gl.createBuffer();
  gl.bindBuffer(gl.ARRAY_BUFFER, buf);
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([
    -1,  1, 0.0, 1.0, 0.0, 1.0, 
     1, -1, 0.0, 1.0, 1.0, 0.0, 
     1,  1, 0.0, 1.0, 1.0, 1.0,
    -1, -1, 0.0, 1.0, 0.0, 0.0,
     1, -1, 0.0, 1.0, 1.0, 0.0,
    -1,  1, 0.0, 1.0, 0.0, 1.0,
  ]), gl.STATIC_DRAW);
    
  gl.bindBuffer(gl.ARRAY_BUFFER, buf);
  let colorPrgPositionLoc = gl.getAttribLocation(colorProgram, "position");
  gl.enableVertexAttribArray(colorPrgPositionLoc);
  gl.vertexAttribPointer(colorPrgPositionLoc, 2, gl.FLOAT, false, 24, 0);

  gl.bindBuffer(gl.ARRAY_BUFFER, buf);
  let colorPrgUvLoc = gl.getAttribLocation(colorProgram, "uv");
  gl.enableVertexAttribArray(colorPrgUvLoc);
  gl.vertexAttribPointer(colorPrgUvLoc, 2, gl.FLOAT, false, 24, 16);

  var textureLoc = gl.getUniformLocation(colorProgram, "in_texture");
  var unit = 2;
  gl.activeTexture(gl.TEXTURE0 + unit);
  gl.bindTexture(gl.TEXTURE_2D, texForRead);
  gl.uniform1i(textureLoc, unit);

  gl.bindFramebuffer(gl.FRAMEBUFFER, texFbPair1.fb);
  gl.viewport(0, 0, width, height);
  gl.drawArrays(gl.TRIANGLES, 0, 6);


  // Prepare to log out the shader program's outputs.
  let fb = texFbPair1.fb
  gl.bindFramebuffer(gl.FRAMEBUFFER, fb)
  let packedRGBA = new Float32Array(width * height * 4);
  gl.readPixels(0, 0, width, height, gl.RGBA, gl.FLOAT, packedRGBA);
  return packedRGBA;
}

let width = 1;
let height = 3672;
let data = new Float32Array(Array.from({length: width * height * 4}, () => Math.random()));
let outputWithTexelFetch = drawTextureAndGetOutput(width, height, data, true);
let outputWithTextureSample = drawTextureAndGetOutput(width, height, data, false);

var compareArrays = function(array0, array1) {
  var mismatchCount = 0;
  for (var i = 0; i < array0.length; ++i) {
    if (array0[i] != array1[i]) {
      console.log("TexelFetch data differs at index " + Math.floor(i/4) + "," + (i%4) + ". Expected:" + array0[i] + " Actual:" + array1[i])
      mismatchCount++;
      if (mismatchCount > 10) {
        break;
      }
    }
  }
}

console.log(">>>>> Comparing outputWithTexelFetch");
compareArrays(data, outputWithTexelFetch);
console.log(">>>>> Comparing outputWithTextureSample");
compareArrays(data, outputWithTextureSample);
console.log(">>>>> Comparing outputWithTexelFetch vs outputWithTextureSample");
compareArrays(outputWithTexelFetch, outputWithTextureSample);
```

**Comment by Linchenn** [comment]
@kenrussell Thank you so much for thinking and investigating in this!

Sorry for confusing you, to help you review, I uploaded my codes [here](https://github.com/Linchenn/Toolkit/blob/main/GPGPU/gpgpu.js).

Currently, for each vertex, I upload xyz and [fix w as 1](https://github.com/Linchenn/Toolkit/blob/main/GPGPU/gpgpu.js#L11). The `vertexBuffer` contains both coords xyz and uv for each vertex:
![image](https://user-images.githubusercontent.com/40653845/187499138-64df9d46-75e6-4ef9-be81-34833899aef7.png)


> Since the results become more and more correct the wider the texture becomes, there might still just be a bug in texture sampling. The number of bits of precision in the tables above should be sufficient to exactly represent all of the values between 0 and 4096. Maybe the bug is actually related to interpolation of varyings for degenerate triangles, if a long skinny triangle is being used to sample the long skinny texture. I'd still suggest trying `texelFetch` and seeing if feeding in appropriate geometry and UVs can reach every texel.

From my understanding, the problem comes from that Mali GPU could not return 3672 interpolation values within range (0, 1) with enough precision, which will be used to calculate index for sampling. Then the index is incorrect.

My demo code above is trying to prove the interpolation values are incorrect for Mali GPU while correct for other GPUs.

**Comment by Linchenn** [comment]
@shanumantesc 

## Aspect ratio may work for most cases
As we previously found, as aspect ratio decreasing, interpolation results become better (we found before). However, I just found, even though the interpolations of [3672, 8], [4095, 8], [3672, 3672] are still incorrect, the calculated indices are correct, because the deviation is too small to be cumulated to affect indices.

To help you check, I created three [tables](https://docs.google.com/spreadsheets/d/1uGfdksY1icQJnWEeV9nVX63DHB6bj-xc2IMTjk0sN-Y/edit?usp=sharing). For each table: the second column is the computed index from varying values; the third and forth columns are ground-truth; the fifth column is the difference between indices. You could find  all difference between indices are 0.

## Potential solutions
So, I am considering three solutions/flags:
1. `TEXTURE_ASPECT_RATIO_THRESHOL` as we mentioned before. From my understanding, the maybe the most effective way because it would not waste storage and it's the most intuitive way, even though we are uncertain if the above analysis covers all cases. 
2. `TEXTURE_EDGE_LENGTH_THRESHOLD_TO_SQUARISH` as we mentioned before. The texture shape will become [power2, size/power2] and this may leave incorrectness to the second edge. It will be hard to maintain and debug in the future.
3. `UPGRADE_TEXTURE_EDGE_THRESHOLD` (default to INF). We may change the solution2 a little bit. If the length of any edge exceed the flag value, we will find a smallest power of 2 value to replace it. I checked it and found it works for [3672,3672] because the texture will be upgraded to [4096, 4096]. I think this solution guarantees correctness, but it wastes memory a lot, so I am not sure if it works for large models when you set the flag.
```js
  if (textureShape[0] > edgeThreshold) {
    const width = nextPowerOf2(textureShape[0]);
    textureShape = [width, Math.ceil(size / width)];
  }

  if (textureShape[1] > edgeThreshold) {
    const height = nextPowerOf2(textureShape[1]);
    textureShape[1] = height;
  }
```

Do you have any suggestions?

**Comment by shanumantesc** [comment]
@Linchenn can you elaborate a bit more on how the numbers in that sheet are calculated? 
Per my understanding, pixel coordinate should be calculated as follows (as I did in the shader above)
```
vec2 centerCoord =  uv * vec2(textureSize);
// use floor to simulate NN interpolation. uvs represent pixel centers whereas pixel origin is at the corner.
ivec2 pixelCoord = ivec2(floor(centerCoord)); 
```
this seems to be close to what your excel formula is doing (`INT(Ax*size)*2`), but I don't understand why we multiply by 2. 

> TEXTURE_ASPECT_RATIO_THRESHOL as we mentioned before. From my understanding, the maybe the most effective way because it would not waste storage and it's the most intuitive way, even though we are uncertain if the above analysis covers all cases. It works for both [3672, 8] and [3672, 3672] without squarish-ing.

If I run my shader above and compare outputs for [3672, 2] , the output matches exactly. So it looks like we will run into sampling issues only for cases where one of the texture dimensions is 1 (I'm calling this 1D texture). And it only starts happening once the texture dimension is above 2879.

I tested the following code:
```
export function getTextureShapeFromLogicalShape(
    logShape: number[], isPacked = false): [number, number] {
  const result = getTextureShapeFromLogicalShapeInternal(logShape, isPacked); // existing TFJS function
  if (Math.max(result[0], result[1]) < 2879) { return result; }
  result[0] = Math.max(isPacked ? 4 : 2, result[0]);
  result[1] = Math.max(isPacked ? 4 : 2, result[1]);
  return result;
}
```

and it produces the correct results on Mali now. So maybe we can expose a flag like `WEBGL_MAX_TEXTURE_DIMENSION_FOR_1D_TEXTURE` and we can set this to `2879` for Mali (potentially we can do it within TFJS source to help all Mali devices). If a texture has max dimension greater than this value, then we just make it 2d by changing the other dimension from 1 to 2.

**Comment by Linchenn** [comment]
> this seems to be close to what your excel formula is doing (`INT(Ax*size)*2`), but I don't understand why we multiply by 2.
It's for packed tensor, since each pixel could store two rows and two columns. You could ignore it, because it would not affect matching.

> So maybe we can expose a flag like `WEBGL_MAX_TEXTURE_DIMENSION_FOR_1D_TEXTURE` and we can set this to `2879` for Mali (potentially we can do it within TFJS source to help all TFJS users). And to be on the safe side, we can have this magic number be `2048` to give us some buffer since we can't realistically test on all Mali devices. If a texture has max dimension greater than this value, then we just make it 2d by changing the other dimension from 1 to 2.

Sounds good! I think this is most intuitive way and it does not hurt perf too much. Will create a PR and cc you. If you see any incorrect values in the future, I am happy to help!

**Comment by kenrussell** [comment]
Apologies for my misunderstanding of how the vertices were set up. Great to hear that you have a feasible workaround!

**Comment by Linchenn** [comment]
> if (Math.max(result[0], result[1]) < 2879) { return result; }

Should 2879 times 2 if packed? @shanumantesc

**Comment by shanumantesc** [comment]
> Should 2879 times 2 if packed?

yep, thanks for noticing

**Comment by Linchenn** [comment]
@shanumantesc 

Just merged the fix PR to our code base. You could try it by locally building or your could wait our tfjs-v3.21.0.

You could use either `tf.env().set('WEBGL_MAX_SIZE_FOR_NARROW_TEXTURE', 2048);` or `tf.env().set('WEBGL_AUTO_SQUARIFY_NARROW_TEXTURE_SHAPE', true);` before running codes on Mali GPU.

**Comment by shanumantesc** [comment]
Thanks for the fix @Linchenn!
