### ISSUE TITLE
CUDA version mismatch

### ISSUE THREAD

**Issue by lukemovement** [tensorflow/tfjs#8362]
The [documentation](https://www.tensorflow.org/install/pip) has recently been updated to instruct the installation of CUDA 12.3, however `@tensorflow/tfjs-node-gpu` seems to be looking for version 11.

```sh
2024-08-24 22:24:04.039287: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda:/usr/local/cuda/lib64:
```

I managed to resolve the first missing file using the command below
```sh
sudo ln -s /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12 /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0
```

For TFJS should we still be using CUDA 11?

**Comment by shmishra99** [comment]
Hi @lukemovement , 

We appreciate you bringing this issue to our attention. Currently `tfjs-node-gpu` 1.2.4 or later supports ` NVIDIA® GPU drivers | >450.x`, `CUDA® Toolkit | 11.2` and `cuDNN SDK | 8.1.0`.  Please refer to the official [documentation](https://github.com/tensorflow/tfjs/tree/master/tfjs-node) for `tfjs-node-gpu` for detailed instructions.

Thank You!!

**Comment by lukemovement** [comment]
> Hi @lukemovement ,
> 
> We appreciate you bringing this issue to our attention. Currently `tfjs-node-gpu` 1.2.4 or later supports ` NVIDIA® GPU drivers | >450.x`, `CUDA® Toolkit | 11.2` and `cuDNN SDK | 8.1.0`. Please refer to the official [documentation](https://github.com/tensorflow/tfjs/tree/master/tfjs-node) for `tfjs-node-gpu` for detailed instructions.
> 
> Thank You!!

Managed to install it on 22.04 follow [this](https://medium.com/@ray.nawfal/installation-instructions-for-tensorflow-pytorch-gpu-enabled-cuda-11-2-6c41f991f068) guide. Might be worth adding it to the documentation considering 20.04 is on its way out?

**Comment by shmishra99** [comment]
I’m pleased to hear that your issue has been resolved. Thank you for your suggestion.
As a reminder, our documentation specifies that for `tfjs/tfjs-node` installations with GPU drivers, `Ubuntu 14.04` or later versions are currently supported. To install the latest TensorFlow version, we recommend `Ubuntu 16.04` or newer.
Please let us know if you have any further questions.
